### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/Tmp/kumarrit/cifar_samples'

### ISSUE THREAD

**Issue by Dear-zhangliyuan** [ritheshkumar95/energy_based_generative_models#6]
when I run the MCMC evalulations on CIFAR data:
I got the error: FileNotFoundError: [Errno 2] No such file or directory: '/Tmp/kumarrit/cifar_samples'
And I noticed that : NOTE: This requires cloning the TTUR repo in the current working directory (https://github.com/bioinf-jku/TTUR).
 I download the repo. But I didn't find the file. 
Can you show me how I can get the  directory: '/Tmp/kumarrit/cifar_samples'?
Look forward to you reply ! Thanks!

**Comment by ritheshkumar95** [comment]
I had hardcoded the path. You can switch it to any folder name you want as long as it exists.
This is just used to store the samples that are temporarily created.
